name: Node.js Artifacts Workflow

on: [push]

jobs:
  build:
    #check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: build.txt

  retrieve-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-log

      - name: List files in the directory
        run: ls -l

      - name: Display contents of the artifact
        run: cat build.txt
